-- Các câu truy vấn đơn giản
-- Câu 1
SELECT MANV, HONV, TENLOT, TENNV
FROM NHANVIEN
WHERE MAPHG = 'NC'

-- Câu 2
SELECT MANV, HONV, TENLOT, TENNV, PHAI
FROM NHANVIEN
WHERE MLUONG > 3000000

-- Câu 3
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN', MAPHG
FROM NHANVIEN
WHERE MLUONG BETWEEN 2000000 AND 3000000

-- Câu 4
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN'
FROM NHANVIEN
WHERE DCHI LIKE'%TPHCM'

-- Câu 5
SELECT NGSINH, DCHI
FROM NHANVIEN
WHERE HONV ='Dinh' AND TENLOT='Ba' AND TENNV='Tien'

--Câu 6
SELECT TENTN
FROM THANNHAN
WHERE YEAR(GETDATE())-YEAR(NGSINH)<18 AND MANV ='001'

--Câu 7
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN'
FROM NHANVIEN
WHERE YEAR(GETDATE())-YEAR(NGSINH)>30 AND PHAI='NU'

-- Phép kết
-- Câu 8
SELECT TENPHG AS 'TENPHONG', DIADIEM AS 'DIADIEM'
FROM PHONGBAN PB, DIADIEM_PHG DD
WHERE PB.MAPHG = DD.MAPHG

-- Câu 9
SELECT MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENTRUONGPHONG', TENPHG AS 'TENPHONGBAN'
FROM PHONGBAN PB, NHANVIEN NV
WHERE PB.TRPHG = NV.MANV

-- Câu 10
SELECT TENDA, MADA, DDIEM_DA, DA.MAPHG, TENPHG, PB.MAPHG, TRPHG,NGNC
FROM PHONGBAN PB, DEAN DA, DIADIEM_PHG DD
WHERE PB.MAPHG = DA.MAPHG AND PB.MAPHG = DD.MAPHG

-- Câu 11
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN', DCHI as 'DIACHI'
FROM PHONGBAN PB, NHANVIEN NV
WHERE PB.MAPHG = NV.MAPHG AND TENPHG = 'Nghien Cuu'

-- Câu 12
SELECT HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN', TENTN AS 'TENTHANNHAN'
FROM THANNHAN TN, NHANVIEN NV
WHERE NV.MANV=TN.MANV AND NV.PHAI = 'Nu'

-- Câu 13
SELECT NV.MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENNHANVIEN'
FROM PHONGBAN PB, NHANVIEN NV, DEAN DA, PHANCONG PC
WHERE PB.MAPHG=NV.MAPHG AND PB.MAPHG=DA.MAPHG AND DA.MADA=PC.MADA AND PC.MANV=NV.MANV AND TENPHG='Nghien Cuu' AND TENDA LIKE 'Tin hoc hoa%' AND THOIGIAN =20

-- Câu 14
SELECT DA.MADA, DA.MAPHG AS 'MAPHONG', HONV + ' ' + TENLOT + ' ' + TENNV AS 'TENTRUONGPHONG', DCHI AS 'DIACHI', NGSINH AS 'NGAYSINH'
FROM PHONGBAN PB, NHANVIEN NV, DEAN DA, PHANCONG PC
WHERE PB.MAPHG = DA.MAPHG AND DA.MADA = PC.MADA AND PC.MANV = PB.TRPHG AND PB.TRPHG = NV.MANV AND DDIEM_DA ='HANOI'

-- Câu 15

-- Câu 16

-- Câu 17

-- Gom nhóm
-- Câu 18
SELECT DA.MADA, TENDA, SUM(THOIGIAN) AS 'TONGSOGIOLAM'
FROM DEAN DA, PHANCONG PC, NHANVIEN NV
WHERE NV.MANV = PC.MANV AND PC.MADA = DA.MADA
GROUP BY DA.MADA,TENDA

-- Câu 19
SELECT NV.MANV, HONV + ' ' + TENLOT + ' ' + TENNV AS 'HOTENNHANVIEN', COUNT(MATN) AS 'TONG_THANNHAN'
FROM NHANVIEN NV, THANNHAN TN
WHERE NV.MANV = TN.MANV
GROUP BY NV.MANV, HONV, TENLOT, TENNV

-- Câu 20

-- Câu 21

-- Câu 22


-- Câu truy vấn lồng

-- Câu 23

-- Câu 24

-- Câu 25

-- Câu 26

-- Câu 27


-- Câu 28

-- Câu 29

-- câu 30

-- Câu 31


-- Phép chia
-- Câu 32

-- Câu 33

-- Câu 34
