USE QLSV_Lenh
GO
-- Làm bài tập tại đây
-- Câu 1
SELECT * FROM SVIEN
WHERE MAKHOA = 'TOAN'

-- Câu 2
SELECT TENMH, TINCHI
FROM MHOC
-- Câu 3
SELECT MSSV, DIEM
FROM KQUA
WHERE MSSV = 'K26.008'
-- Câu 4
SELECT TENSV, MAMH, DIEM
FROM SINHVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV 
WHERE KQ.DIEM > 7
-- Câu 5
SELECT TENSV
FROM SVIEN SV, MHOC MH
WHERE TENMH = 'Toan roi rac' AND SV.MAKHOA = MH.MAKH
-- Câu 6
SELECT TENSV, TENMH, DIEM
FROM KQUA KQ, SVIEN SV, HPHAN HP, MHOC MH
WHERE HP.HOCKY = 1 AND HP.NAM = 1996 AND SV.MASV = KQ.MASV AND KQ.MAHP = HP.MAHP AND HP.MAHP = MH.MAHP
-- Câu 7
SELECT TENMH 
FROM MHOC
WHERE MAMH IN (
    SELECT DK MAMH_TRUOC
    FROM DKIEN DK JOIN MHOC MH ON DK.MAMH = MH.MAMH
    WHERE MH.TEN LIKE 'Co so du lieu'
)
-- Câu 8
SELECT MH2.TENMH
FROM MHOC MH1, MHOC MH2, DIEM
WHERE MH1.TENMH = 'Co so du lieu' AND MH1.MAMH = DKIEN.MAMH_TRUOC AND DKIEN.MAMH = MH2.MAMH
-- Câu 9
SELECT mh.TENMH 
FROM MHOC mh, DKIEN dk
WHERE mh.MAMH = dk.MAMH_TRUOC AND mh.MAMH IN (
    SELECT dk.MAMH_TRUOC FROM MHOC, DKIEN
    WHERE mh.TINCHI <= 4 AND dk.MAMH = mh.MAMH
)
-- Câu 10
-- SELECT TENSV, DIEM FROM KQUA kq, SVIEN sv, HPHAN hp, MHOC mh
-- WHERE sv.MASV = kq.MASV AND kq.MAHP = 
-- Câu 11
SELECT MAHP, COUNT(MASV) SOLUONGSV
FROM KQUA
GROUP BY MAHP
-- Câu 12
SELECT sv.TENSV, AVG(DIEM) DIEMAVG, hp.HOCKY, hp.NAM
FROM SVIEN sv JOIN KQUA kq ON sv.MASV = kq.MASV
-- Câu 13
SELECT TOP(1) WITH TIES TENSV, DIEM
FROM SVIEN SV JOIN KQUA KQ ON SV.MASV = KQ.MASV 
ORDER BY DIEM DESC
-- Câu 14

-- Câu 15

-- Câu 16

-- Câu 17

-- Câu 18
SELECT * FROM MHOC mh
WHERE mh.MAKHOA like 'TOAN' AND mh.MAMH NOT IN (
    SELECT hp.MAMH FROM HPHAN hp
    WHERE hp.HOCKY = 1 AND hp.NAM = 1996
    AND hp.MAMH = mh.MAMH
)

-- Câu 19
SELECT * FROM SVIEN sv
WHERE sv.MAKHOA = 'TOAN'
AND sv.NAM = 3
AND sv.MASV NOT IN (
    SELECT sv.MASV FROM KQUA kq, HPHAN hp, MHOC mh
    WHERE mh.TENMH like 'Cơ sở dữ liệu' 
    AND hp.HOCKY = 1 AND hp.NAM = 1996
    AND mh.MAMH = hp.MAMH
    AND hp.MAHP = kq.MAHP
    AND kq.MASV = sv.MASV
)

-- Câu 20
SELECT * FROM SVIEN sv ,(
    SELECT kq.MASV 'MASV', COUNT(*) 'COUNT' FROM KQUA kq, HPHAN hp
    WHERE hp.HOCKY = 1 AND hp.NAM = 1996
    AND hp.MAHP = kq.MAHP
    GROUP BY kq.MASV
) tb2
WHERE tb2.COUNT >= 3 AND sv.MASV = tb2.MASV
